from common.site import chunk_keyword


chunk_prefix_len = 20

'''
First 20 symbols of each chunk document,
excluding extra white spaces.
Uncommon apostrophes ‘ and ’
are replaced with common ones '.
'''
chunk_prefixes = {
  chunk_keyword + ' pmrt u u.' : 1,
  chunk_keyword + ' emk--thra' : 2,
  chunk_keyword + ' aff cguqt' : 3,
  chunk_keyword + ' m hush fq' : 4,
  chunk_keyword + ' xmndrm, m' : 5,
  chunk_keyword + ' m paunt, ' : 6,
  chunk_keyword + ' qymrwqd. ' : 7,
  chunk_keyword + ' ud thq sq' : 8,
  chunk_keyword + ' iuth hue ' : 9,
  chunk_keyword + ' i iandqrf' : 10,
  chunk_keyword + ' qxmyplq a' : 11,
  chunk_keyword + ' hmrdlk hm' : 12,
  chunk_keyword + ' d huyeqlf' : 13,
  chunk_keyword + ' mt thq qn' : 14,
  chunk_keyword + ' ta m ymrr' : 15,
  chunk_keyword + ' e m kagns' : 16,
  chunk_keyword + ' iuth huy,' : 17,
  chunk_keyword + ' qeeuan im' : 18,
  chunk_keyword + ' tqrfmll n' : 19,
  chunk_keyword + ' oagld luv' : 20,
  chunk_keyword + ' kqt! ihqn' : 21,
  chunk_keyword + ' ldrqn. qv' : 22,
  chunk_keyword + ' d--far th' : 23,
  chunk_keyword + ' tqr hqr m' : 24,
  chunk_keyword + ' nd kag yg' : 25,
  chunk_keyword + ' , bgt etu' : 26,
  chunk_keyword + ' nai thq d' : 27,
  chunk_keyword + ' ar yq. iq' : 28,
  chunk_keyword + ' mnd thmt,' : 29,
  chunk_keyword + ' untqrqet.' : 30,
  chunk_keyword + ' thagsh hq' : 31,
  chunk_keyword + ' emk \'_cg\'' : 32, # ' emk ‘_cg’'
  chunk_keyword + ' d smnum. ' : 33,
  chunk_keyword + ' qxmndravn' : 34,
  chunk_keyword + ' q hme rqt' : 35,
  chunk_keyword + ' s iuth ms' : 36,
  chunk_keyword + ' qbqdqff e' : 37,
  chunk_keyword + ' uth eayq ' : 38,
  chunk_keyword + ' hq raay. ' : 39,
  chunk_keyword + ' thmn qpmn' : 40,
  chunk_keyword + ' rq kag ut' : 41,
  chunk_keyword + ' t ihmt m ' : 42,
  chunk_keyword + ' un mt mll' : 43,
  chunk_keyword + ' mot thmt ' : 44,
  chunk_keyword + ' tqn thqk ' : 45,
  chunk_keyword + ' bq dueabl' : 46,
  chunk_keyword + ' trqee, uf' : 47,
  chunk_keyword + ' fmyulk, f' : 48,
  chunk_keyword + ' frmud ut ' : 49,
  chunk_keyword + ' thq yqn, ' : 50,
  chunk_keyword + ' hmt hue h' : 51,
  chunk_keyword + ' hue hmppk' : 52,
  chunk_keyword + ' hqr oayyg' : 53,
  chunk_keyword + ' , mnd ut ' : 54,
  chunk_keyword + ' ; bgt u d' : 55,
  chunk_keyword + ' rnuns far' : 56,
  chunk_keyword + ' dmyeqle, ' : 57,
  chunk_keyword + ' bjqot. hq' : 58,
  chunk_keyword + ' thq sqnqr' : 59,
  chunk_keyword + ' kqe, mnd ' : 60,
  chunk_keyword + ' hgndrqd r' : 61,
  chunk_keyword + ' agt mll n' : 62,
  chunk_keyword + ' . lqbqdqf' : 63,
  chunk_keyword + ' q hmur; h' : 64,
  chunk_keyword + ' thqk hmd ' : 65,
  chunk_keyword + ' und, mnd ' : 66,
  chunk_keyword + ' rushtqnqd' : 67,
  chunk_keyword + ' gr fmthqr' : 68,
  chunk_keyword + ' p iuth ea' : 69,
  chunk_keyword + ' bqfarq u ' : 70,
  chunk_keyword + ' qrq ime n' : 71,
  chunk_keyword + ' e uf u gn' : 72,
  chunk_keyword + ' mnd putk;' : 73,
  chunk_keyword + ' qeqntuyqn' : 74,
  chunk_keyword + ' udq tqrrm' : 75,
  chunk_keyword + ' , ut ue m' : 76,
  chunk_keyword + ' wafuqvnm,' : 77,
  chunk_keyword + ' eouqnoq r' : 78,
  chunk_keyword + ' thq wnush' : 79,
  chunk_keyword + ' ime m rqo' : 80,
  chunk_keyword + ' hqmrd af ' : 81,
  chunk_keyword + ' ow, mnd h' : 82,
  chunk_keyword + ' eum, iqmr' : 83,
  chunk_keyword + ' ne af tha' : 84,
  chunk_keyword + ' ull da, l' : 85,
  chunk_keyword + ' --iqll, t' : 86,
  chunk_keyword + ' agemnd ra' : 87,
  chunk_keyword + ' affqrqd h' : 88,
  chunk_keyword + ' hqr, bgt ' : 89,
  chunk_keyword + ' oantqnte ' : 90,
  chunk_keyword + ' lq yqmnun' : 91,
  chunk_keyword + ' thmt u eh' : 92,
  chunk_keyword + ' mnsrulk, ' : 93,
  chunk_keyword + ' rusht mba' : 94,
  chunk_keyword + ' qn imryth' : 95,
  chunk_keyword + ' kag hmvq ' : 96,
  chunk_keyword + ' tqll kag ' : 97,
  chunk_keyword + ' qrkanq im' : 98,
  chunk_keyword + ' ygoh?” “u' : 99,
  chunk_keyword + ' pqaplq un' : 100,
  chunk_keyword + ' mppqmrqd!' : 101,
  chunk_keyword + ' gt u\'ll t' : 102, # ' gt u’ll t'
  chunk_keyword + ' \'t--” “da' : 103, # ' ’t--” “da’'
  chunk_keyword + ' qet dmgsh' : 104,
  chunk_keyword + ' qe, mt tq' : 105,
  chunk_keyword + ' hq iqrq l' : 106,
  chunk_keyword + ' fqllai!” ' : 107,
  chunk_keyword + ' d u fqql ' : 108,
  chunk_keyword + ' a qxplmun' : 109,
  chunk_keyword + ' n. mslmkm' : 110,
  chunk_keyword + ' qnd gpan ' : 111,
  chunk_keyword + ' qmrqd mlt' : 112,
  chunk_keyword + ' eagnde af' : 113,
  chunk_keyword + ' ml. u far' : 114,
  chunk_keyword + ' lqft ta h' : 115,
  chunk_keyword + ' q iagld h' : 116,
  chunk_keyword + ' dan\'t fra' : 117, # ' dan’t fra'
  chunk_keyword + ' oq smthqr' : 118,
  chunk_keyword + ' oh untqrq' : 119,
  chunk_keyword + ' emyq tuyq' : 120,
  chunk_keyword + ' udqeprqmd' : 121,
  chunk_keyword + ' apunuan, ' : 122,
  chunk_keyword + ' uns. “kqe' : 123,
  chunk_keyword + ' d me ehq ' : 124,
  chunk_keyword + ' ea thmt y' : 125,
  chunk_keyword + ' alktq, br' : 126,
  chunk_keyword + ' q bqfarq ' : 127,
  chunk_keyword + ' qr, bgt s' : 128,
  chunk_keyword + ' m yqduoml' : 129,
  chunk_keyword + ' nqd thmt ' : 130,
  chunk_keyword + ' nt af yk ' : 131,
  chunk_keyword + ' egbardunm' : 132,
  chunk_keyword + ' ymsunqe a' : 133,
  chunk_keyword + ' ihk thue ' : 134,
  chunk_keyword + ' gr ain ew' : 135,
  chunk_keyword + ' ihulq thq' : 136,
  chunk_keyword + ' qur rqndq' : 137,
  chunk_keyword + ' anvunoqd,' : 138,
  chunk_keyword + ' lk. “prun' : 139,
  chunk_keyword + ' ud af emk' : 140,
  chunk_keyword + ' ar hqr? k' : 141,
  chunk_keyword + ' rthqr, mn' : 142,
  chunk_keyword + ' thq \'qxpl' : 143, # ' thq ‘qxpl'
  chunk_keyword + ' e. “mll r' : 144,
  chunk_keyword + ' mt hqmd? ' : 145,
  chunk_keyword + ' mrq nat t' : 146,
  chunk_keyword + ' mttqypt t' : 147,
  chunk_keyword + ' n--” “ymy' : 148,
  chunk_keyword + ' ll m navq' : 149,
  chunk_keyword + ' t hue bge' : 150,
  chunk_keyword + ' hq mddqd,' : 151,
  chunk_keyword + ' “ihmt! _m' : 152,
  chunk_keyword + ' ar thue--' : 153,
  chunk_keyword + ' h mn qxoq' : 154,
  chunk_keyword + ' qr. ut la' : 155,
  chunk_keyword + ' yarq oayp' : 156,
  chunk_keyword + ' g gndqret' : 157,
  chunk_keyword + ' hmnw sad ' : 158,
  chunk_keyword + ' ; far ta ' : 159,
  chunk_keyword + ' q, iq iqr' : 160,
  chunk_keyword + ' af thq qy' : 161,
  chunk_keyword + ' hue qkqe.' : 162,
  chunk_keyword + ' f m hageq' : 163,
  chunk_keyword + ' ta thmt “' : 164,
  chunk_keyword + ' p huy!” o' : 165,
  chunk_keyword + ' hagsh u m' : 166,
  chunk_keyword + ' mnkthuns ' : 167,
  chunk_keyword + ' thmt hq i' : 168,
  chunk_keyword + ' ime m yay' : 169,
  chunk_keyword + ' hmt iagld' : 170,
  chunk_keyword + ' qd; thq p' : 171,
  chunk_keyword + ' munfgl ta' : 172,
  chunk_keyword + ' bulutk im' : 173,
  chunk_keyword + ' k, hue lq' : 174,
  chunk_keyword + ' hm, hm.) ' : 175,
  chunk_keyword + ' fgrthqr; ' : 176,
  chunk_keyword + ' hqeq iard' : 177,
  chunk_keyword + ' kqmre--kq' : 178,
  chunk_keyword + ' ag ta bq ' : 179,
  chunk_keyword + ' qf ime rm' : 180,
  chunk_keyword + ' an qxmotl' : 181,
  chunk_keyword + ' g wnai na' : 182,
  chunk_keyword + ' tq, laawu' : 183,
  chunk_keyword + ' laawuns, ' : 184,
  chunk_keyword + ' agsht gp ' : 185,
  chunk_keyword + ' r prqeqno' : 186,
  chunk_keyword + ' dk. bgt l' : 187,
  chunk_keyword + ' qy. ut im' : 188,
  chunk_keyword + ' nat msrqq' : 189,
  chunk_keyword + ' , yk ymrr' : 190,
  chunk_keyword + ' --” “ue u' : 191,
  chunk_keyword + ' anlk yanq' : 192,
  chunk_keyword + ' pmet thqu' : 193,
  chunk_keyword + ' eqrvqd m ' : 194,
  chunk_keyword + ' k hmd san' : 195,
  chunk_keyword + ' bgek. qvq' : 196,
  chunk_keyword + ' wuns mbag' : 197,
  chunk_keyword + ' ta thq pr' : 198,
  chunk_keyword + ' agt, ehq\'' : 199, # ' agt, ehq’'
  chunk_keyword + ' hue vuqi,' : 200,
}
